export const json = {
    completeText: 'Hoàn thành',
    pageNextText: 'Tiếp',
    pagePrevText: 'Lùi',
    pages: [
        {
            name: 'page1',
            title: 'Suy nghĩ và Cảm giác',
            elements: [
                {
                    type: 'radiogroup',
                    name: 'buồn',
                    title: 'Cảm thấy buồn bã',
                    choices: [
                        { value: 4, text: 'Rất nhiều' },
                        { value: 3, text: 'Nhiều' },
                        { value: 2, text: 'Vừa vừa' },
                        { value: 1, text: 'Có chút chút' },
                        { value: 0, text: 'Không hề' },
                    ],
                    colCount: 5,
                    isRequired: true,
                },
                {
                    type: 'radiogroup',
                    name: 'không vui',
                    title: 'Cảm thấy không vui',
                    choices: [
                        { value: 4, text: 'Rất nhiều' },
                        { value: 3, text: 'Nhiều' },
                        { value: 2, text: 'Vừa vừa' },
                        { value: 1, text: 'Có chút chút' },
                        { value: 0, text: 'Không hề' },
                    ],
                    colCount: 5,
                    isRequired: true,
                },
                {
                    type: 'radiogroup',
                    name: 'khóc',
                    title: 'Cảm thấy muốn khóc',
                    choices: [
                        { value: 4, text: 'Rất nhiều' },
                        { value: 3, text: 'Nhiều' },
                        { value: 2, text: 'Vừa vừa' },
                        { value: 1, text: 'Có chút chút' },
                        { value: 0, text: 'Không hề' },
                    ],
                    colCount: 5,
                    isRequired: false,
                },
                {
                    type: 'radiogroup',
                    name: 'chán nản',
                    title: 'Cảm thấy chán nản',
                    choices: [
                        { value: 4, text: 'Rất nhiều' },
                        { value: 3, text: 'Nhiều' },
                        { value: 2, text: 'Vừa vừa' },
                        { value: 1, text: 'Có chút chút' },
                        { value: 0, text: 'Không hề' },
                    ],
                    colCount: 5,
                    isRequired: false,
                },
                {
                    type: 'radiogroup',
                    name: 'vô vọng',
                    title: 'Cảm thấy vô vọng',
                    choices: [
                        { value: 4, text: 'Rất nhiều' },
                        { value: 3, text: 'Nhiều' },
                        { value: 2, text: 'Vừa vừa' },
                        { value: 1, text: 'Có chút chút' },
                        { value: 0, text: 'Không hề' },
                    ],
                    colCount: 5,
                    isRequired: false,
                },
                {
                    type: 'radiogroup',
                    name: 'không còn tự trọng',
                    title: 'Thấy lòng tự trọng không còn nữa',
                    choices: [
                        { value: 4, text: 'Rất nhiều' },
                        { value: 3, text: 'Nhiều' },
                        { value: 2, text: 'Vừa vừa' },
                        { value: 1, text: 'Có chút chút' },
                        { value: 0, text: 'Không hề' },
                    ],
                    colCount: 5,
                    isRequired: false,
                },
                {
                    type: 'radiogroup',
                    name: 'vô dụng hoặc kém cỏi',
                    title: 'Thấy mình vô dụng hoặc kém cỏi',
                    choices: [
                        { value: 4, text: 'Rất nhiều' },
                        { value: 3, text: 'Nhiều' },
                        { value: 2, text: 'Vừa vừa' },
                        { value: 1, text: 'Có chút chút' },
                        { value: 0, text: 'Không hề' },
                    ],
                    colCount: 5,
                    isRequired: false,
                },
                {
                    type: 'radiogroup',
                    name: 'tội lỗi, xấu hổ với bản thân và mọi người',
                    title: 'Thấy tội lỗi, xấu hổ với bản thân và mọi người',
                    choices: [
                        { value: 4, text: 'Rất nhiều' },
                        { value: 3, text: 'Nhiều' },
                        { value: 2, text: 'Vừa vừa' },
                        { value: 1, text: 'Có chút chút' },
                        { value: 0, text: 'Không hề' },
                    ],
                    colCount: 5,
                    isRequired: false,
                },
                {
                    type: 'radiogroup',
                    name: 'tự chỉ trích, lên án bản thân',
                    title: 'Luôn tự chỉ trích, lên án bản thân',
                    choices: [
                        { value: 4, text: 'Rất nhiều' },
                        { value: 3, text: 'Nhiều' },
                        { value: 2, text: 'Vừa vừa' },
                        { value: 1, text: 'Có chút chút' },
                        { value: 0, text: 'Không hề' },
                    ],
                    colCount: 5,
                    isRequired: false,
                },
                {
                    type: 'radiogroup',
                    name: 'tự đưa ra quyết định',
                    title: 'Khó có thể tự đưa ra quyết định nào',
                    choices: [
                        { value: 4, text: 'Rất nhiều' },
                        { value: 3, text: 'Nhiều' },
                        { value: 2, text: 'Vừa vừa' },
                        { value: 1, text: 'Có chút chút' },
                        { value: 0, text: 'Không hề' },
                    ],
                    colCount: 5,
                    isRequired: false,
                },
            ],
        },
        {
            name: 'page2',
            title: 'Hoạt động và mối quan hệ cá nhân',
            elements: [
                {
                    type: 'radiogroup',
                    name: 'hứng thú với gia đình, bạn bè, đồng nghiệp',
                    title: 'Mất hứng thú với gia đình, bạn bè, đồng nghiệp',
                    choices: [
                        { value: 4, text: 'Rất nhiều' },
                        { value: 3, text: 'Nhiều' },
                        { value: 2, text: 'Vừa vừa' },
                        { value: 1, text: 'Có chút chút' },
                        { value: 0, text: 'Không hề' },
                    ],
                    colCount: 5,
                    isRequired: false,
                },
                {
                    type: 'radiogroup',
                    name: 'cô đơn',
                    title: 'Cảm thấy cô đơn',
                    choices: [
                        { value: 4, text: 'Rất nhiều' },
                        { value: 3, text: 'Nhiều' },
                        { value: 2, text: 'Vừa vừa' },
                        { value: 1, text: 'Có chút chút' },
                        { value: 0, text: 'Không hề' },
                    ],
                    colCount: 5,
                    isRequired: false,
                },
                {
                    type: 'radiogroup',
                    name: 'thời gian cho gia đình',
                    title: 'Dành ít hoặc không dành thời gian cho gia đình',
                    choices: [
                        { value: 4, text: 'Rất nhiều' },
                        { value: 3, text: 'Nhiều' },
                        { value: 2, text: 'Vừa vừa' },
                        { value: 1, text: 'Có chút chút' },
                        { value: 0, text: 'Không hề' },
                    ],
                    colCount: 5,
                    isRequired: false,
                },
                {
                    type: 'radiogroup',
                    name: 'động lực',
                    title: 'Không còn tí động lực nào nữa',
                    choices: [
                        { value: 4, text: 'Rất nhiều' },
                        { value: 3, text: 'Nhiều' },
                        { value: 2, text: 'Vừa vừa' },
                        { value: 1, text: 'Có chút chút' },
                        { value: 0, text: 'Không hề' },
                    ],
                    colCount: 5,
                    isRequired: false,
                },
                {
                    type: 'radiogroup',
                    name: 'hứng thú trong công việc hay hoạt động khác',
                    title: 'Mất hứng thú trong công việc hay hoạt động khác',
                    choices: [
                        { value: 4, text: 'Rất nhiều' },
                        { value: 3, text: 'Nhiều' },
                        { value: 2, text: 'Vừa vừa' },
                        { value: 1, text: 'Có chút chút' },
                        { value: 0, text: 'Không hề' },
                    ],
                    colCount: 5,
                    isRequired: false,
                },
                {
                    type: 'radiogroup',
                    name: 'công việc',
                    title: 'Né tránh công việc, không thích làm gì cả',
                    choices: [
                        { value: 4, text: 'Rất nhiều' },
                        { value: 3, text: 'Nhiều' },
                        { value: 2, text: 'Vừa vừa' },
                        { value: 1, text: 'Có chút chút' },
                        { value: 0, text: 'Không hề' },
                    ],
                    colCount: 5,
                    isRequired: false,
                },
                {
                    type: 'radiogroup',
                    name: 'niềm vui',
                    title: 'Mất niềm vui, mất đi sự thoả mãn trong cuộc sống',
                    choices: [
                        { value: 4, text: 'Rất nhiều' },
                        { value: 3, text: 'Nhiều' },
                        { value: 2, text: 'Vừa vừa' },
                        { value: 1, text: 'Có chút chút' },
                        { value: 0, text: 'Không hề' },
                    ],
                    colCount: 5,
                    isRequired: false,
                },
            ],
        },
        {
            name: 'page3',
            title: 'Các triệu chứng về thể chất',
            elements: [
                {
                    type: 'radiogroup',
                    name: 'mệt mỏi tột độ',
                    title: 'Cảm thấy mệt mỏi tột độ',
                    choices: [
                        { value: 4, text: 'Rất nhiều' },
                        { value: 3, text: 'Nhiều' },
                        { value: 2, text: 'Vừa vừa' },
                        { value: 1, text: 'Có chút chút' },
                        { value: 0, text: 'Không hề' },
                    ],
                    colCount: 5,
                    isRequired: false,
                },
                {
                    type: 'radiogroup',
                    name: 'ngủ',
                    title: 'Khó ngủ hoặc ngủ quá nhiều',
                    choices: [
                        { value: 4, text: 'Rất nhiều' },
                        { value: 3, text: 'Nhiều' },
                        { value: 2, text: 'Vừa vừa' },
                        { value: 1, text: 'Có chút chút' },
                        { value: 0, text: 'Không hề' },
                    ],
                    colCount: 5,
                    isRequired: false,
                },
                {
                    type: 'radiogroup',
                    name: 'ăn',
                    title: 'Lúc thèm ăn, lúc chán ăn',
                    choices: [
                        { value: 4, text: 'Rất nhiều' },
                        { value: 3, text: 'Nhiều' },
                        { value: 2, text: 'Vừa vừa' },
                        { value: 1, text: 'Có chút chút' },
                        { value: 0, text: 'Không hề' },
                    ],
                    colCount: 5,
                    isRequired: false,
                },
                {
                    type: 'radiogroup',
                    name: 'sex',
                    title: 'Mất hứng thú với tình dục',
                    choices: [
                        { value: 4, text: 'Rất nhiều' },
                        { value: 3, text: 'Nhiều' },
                        { value: 2, text: 'Vừa vừa' },
                        { value: 1, text: 'Có chút chút' },
                        { value: 0, text: 'Không hề' },
                    ],
                    colCount: 5,
                    isRequired: false,
                },
                {
                    type: 'radiogroup',
                    name: 'sức khoẻ bản thân',
                    title: 'Lo lắng về sức khoẻ bản thân',
                    choices: [
                        { value: 4, text: 'Rất nhiều' },
                        { value: 3, text: 'Nhiều' },
                        { value: 2, text: 'Vừa vừa' },
                        { value: 1, text: 'Có chút chút' },
                        { value: 0, text: 'Không hề' },
                    ],
                    colCount: 5,
                    isRequired: false,
                },
            ],
        },
        {
            name: 'page4',
            title: 'Thôi thúc muốn tự sát',
            elements: [
                {
                    type: 'radiogroup',
                    name: 'suy nghĩ đến việc tự sát',
                    title: 'Bạn có suy nghĩ đến việc tự sát không?',
                    choices: [
                        { value: 4, text: 'Rất nhiều' },
                        { value: 3, text: 'Nhiều' },
                        { value: 2, text: 'Vừa vừa' },
                        { value: 1, text: 'Có chút chút' },
                        { value: 0, text: 'Không hề' },
                    ],
                    colCount: 5,
                    isRequired: false,
                },
                {
                    type: 'radiogroup',
                    name: 'kết thúc cuộc đời',
                    title: 'Bạn có muốn kết thúc cuộc đời mình không?',
                    choices: [
                        { value: 4, text: 'Rất nhiều' },
                        { value: 3, text: 'Nhiều' },
                        { value: 2, text: 'Vừa vừa' },
                        { value: 1, text: 'Có chút chút' },
                        { value: 0, text: 'Không hề' },
                    ],
                    colCount: 5,
                    isRequired: false,
                },
                {
                    type: 'radiogroup',
                    name: 'làm hại bản thân',
                    title: 'Bạn có kế hoạch làm hại bản thân mình không thế',
                    choices: [
                        { value: 4, text: 'Rất nhiều' },
                        { value: 3, text: 'Nhiều' },
                        { value: 2, text: 'Vừa vừa' },
                        { value: 1, text: 'Có chút chút' },
                        { value: 0, text: 'Không hề' },
                    ],
                    colCount: 5,
                    isRequired: false,
                },
            ],
        },
    ],
    showProgressBar: 'top',
    progressBarType: 'questions',
    widthMode: 'static',
    width: '864px',
};
